DROP TABLE IF EXISTS ark_address;
CREATE TABLE ark_address (
  id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  address VARCHAR(34) NOT NULL,
  passphrase TEXT NULL,
  balance BIGINT NOT NULL DEFAULT 0,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS receiver;
CREATE TABLE receiver (
  id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  email VARCHAR(200) NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS ark_transaction;
CREATE TABLE ark_transaction (
  id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  -- email VARCHAR(200) NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS ark_forward;
CREATE TABLE ark_forward (
  id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  sender_name VARCHAR(100) NULL,
  return_address_id BIGINT NULL,
  receiver_id BIGINT NOT NULL,
  receiver_amount BIGINT NOT NULL DEFAULT 0,
  fee_amount BIGINT NOT NULL DEFAULT 0,
  total_amount BIGINT NOT NULL DEFAULT 0,
  deposit_address_id BIGINT NULL,
  cancel_password VARCHAR(100) NOT NULL,
  accept_key VARCHAR(100) NOT NULL,
  transaction_id BIGINT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'CREATED',
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (return_address_id) REFERENCES ark_address (id),
  FOREIGN KEY (deposit_address_id) REFERENCES ark_address (id),
  FOREIGN KEY (transaction_id) REFERENCES ark_transaction (id)
) DEFAULT CHARSET=utf8;

