DROP TABLE IF EXISTS ark_address;
CREATE TABLE ark_address (
  id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  address VARCHAR(34) NOT NULL,
  password TEXT NULL,
  balance BIGINT NOT NULL DEFAULT 0,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8 COLLATE utf8_unicode_ci;

